(function_item name: (identifier) @name) @def.fn
(function_signature_item name: (identifier) @name) @def.fn
(impl_item type: (type_identifier) @name) @def.impl
(struct_item name: (type_identifier) @name) @def.struct
(enum_item name: (type_identifier) @name) @def.enum
(trait_item name: (type_identifier) @name) @def.trait
(type_item name: (type_identifier) @name) @def.type
(const_item name: (identifier) @name) @def.const
(static_item name: (identifier) @name) @def.static
(mod_item name: (identifier) @name) @def.mod
(macro_definition name: (identifier) @name) @def.macro
